name: Deploy on Prod

on:
  workflow_dispatch:

env:
  PROJECT_ID: the-mee-foundation
  HOST: sdk.mee.foundation
  BUCKET_NAME: sdk-mee-foundation-bucket

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build

      - name: configure gcp credentials
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1043231896197/locations/global/workloadIdentityPools/github-actions-pool/providers/github"
          service_account: "github-actions@$PROJECT_ID.iam.gserviceaccount.com"

      - name: deploy to bucket
        run: |
          gcloud storage rsync --recursive ./dist gs://$BUCKET_NAME
          gcloud storage objects update --content-type="text/html" --cache-control="public, max-age=60" --content-disposition="" gs://$BUCKET_NAME/*.{js,ts}
          gcloud compute url-maps invalidate-cdn-cache prod-url-map --project $PROJECT_ID --path "/index.html" --host "$HOST" --async 